name: Preview SDKs

on:
  pull_request:
    paths:
      - "fern/definition/**"
      - "fern/generators.yml"

jobs:
  preview-typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Generate Preview
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --group ts-sdk --preview --log-level debug --api version-2024-06-10

      - name: Compile
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          cd fern/apis/version-2024-06-10/.preview/fern-typescript-node-sdk
          yarn install
          yarn build

  preview-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Preview Python SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --group python-sdk --preview --log-level debug --api version-2024-11-13

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Bootstrap poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y --version 1.5.1

      - name: Compile
        run: |
          cd fern/apis/version-2024-11-13/.preview/fern-python-sdk
          poetry install
          poetry run mypy .
